### ISSUE TITLE
Bug:  Cannot autocomplete 'transmit' command

### ISSUE THREAD

**Issue by SoopCanSam** [IlyaChichkov/LethalAutocompleteMod#12]
When starting to type out "transmit" in the terminal it can't be autocompleted using tab like the other commands can. I have the Signal Translator purchased when attempting this. 

My modlist ThunderStore import code if you want to look: 018d9639-4d09-f901-124b-0ae3d9c2fa0e
Although, I highly doubt it is another mod.

**Comment by IlyaChichkov** [comment]
Hello, it seems to me that there is no word in auto-completion because in the game the transmit command is separate from the other commands and therefore is not added to the list. You can add any word for auto-completion via the save file.json, the path to it is specified in the configuration settings.

Here is an example with the transmit command:

> {
>   "Words": [
>     {
>       "Word": "transmit",
>       "Children": [],
>       "Weight": 10
>     },
>     {
>       "Word": "Confirm",
>       "Children": [],
>       "Weight": 20
>     },
>     ...

**Comment by IlyaChichkov** [comment]
Another option is to replace your file with this one:

[save.json](https://github.com/IlyaChichkov/LethalAutocompleteMod/files/14402711/save.json)

Sorry for the delay in responding
